apiVersion: v1
kind: Service
metadata:
  name: article-preview-component
  namespace: default
spec:
  selector:
    app: article-preview-component-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
